src/theflow/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin

from django.contrib import admin
admin.autodiscover()

from views import HomeView
from views import MainView
from views import LogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #------------------------------------------------------------------------------------------------------------------------
    #    "home"
    url(r'^$', HomeView.as_view(), name='home'),
    
    #------------------------------------------------------------------------------------------------------------------------
    #    "main"
    url(r'^main/$', MainView.as_view(), name='main'),
    
    #------------------------------------------------------------------------------------------------------------------------
    #    login - logout
    url(r'^login/$', auth_views.login, { 'template_name' : 'pages/login.html' }, name = 'login'),

    #     logout user
    url(r'^logout/?$', LogoutView.as_view(), name = 'logout'),

    #------------------------------------------------------------------------------------------------------------------------
    #    userprofile app's URLs
    url(r'^userprofile/', include('userprofile.urls', namespace = 'userprofile')),

]

src/userprofile/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from django.contrib import admin
admin.autodiscover()

from .views import UserProfileView
from .views import UserProfileEdit
from .views import LogoutView
from .views import NewUserView

urlpatterns = [

    #     view user profile
    url(r'^$', UserProfileView.as_view(), name = 'view'),

    #    edit user profile
    url(r'^edit/?$', UserProfileEdit.as_view(), name = 'edit'),

    #    new user
    url(r'^new/?$', NewUserView.as_view(), name = 'new'),

    #     logout user
    url(r'^logout/?$', LogoutView.as_view(), name = 'logout'),

]

src/templates/pages/error.html
{% extends "pages/template-base.html" %}
{% load static %}

{% block content %}
    <div class="col-md-12">
        <h4 class="bg-danger">ERROR</h4>
    </div>
{% endblock %}

src/templates/pages/home.html
{% extends "pages/template-base.html" %}
{% load static %}

{% block content %}
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <ul class="list-unstyled">
            <li>
                <br/>
                <h2 class="text-center">Welcome to FLOW</h2>
            </li>

            <li>
                <br/>
                <a class="btn btn-info btn-lg btn-block" href="{% url 'login' %}">LOGIN</a>
            </li>
        </ul>
    </div>
    <div class="col-md-4"></div>
{% endblock %}

src/templates/pages/login.html
{% extends "pages/template-base.html" %}
{% load static %}

{% block content %}
    <br/>
    <div class="col-md-5">
        {% if form.errors %}
        <div class="alert alert-danger text-center">
            <h5>Invalid <br> Username/Password</h5>
        </div>
        {% endif %}
    </div>
    
    <div class="col-md-2 text-center">
        <form id="form_login" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            
            <div class="row">
                <div class="col-md-12">
                    <input id="id_username" maxlength="50" name="username" 
                           type="text" placeholder="Username" autofocus='true' class="form-control form-input">
                </div>
            </div>
            <br/>
            
            <div class="row">
                <div class="col-md-12">
                    <input id="id_password" name="password" type="password" 
                           placeholder="Password" class="form-control form-input">
                </div>
            </div>

            <br/>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-success btn-block">Enter</i></button>
                </div>
            </div>
            <br/>
        </form>
    </div>

    <div class="col-md-5">
    </div>
{% endblock %}

src/templates/pages/main.html
{% extends "pages/template-base.html" %}
{% load static %}

{% block content %}
    <div class="col-md-4">
    </div>
    <div class="col-md-8">
        <br/>
        <ul class="list-inline">
            <li><h4>MAIN</h4></li>
            <li>·</li>
            <li><a href="{% url 'userprofile:view' %}"><h4>userprofile</h4></a></li>
            <li>·</li>
            <li><a href="{% url 'logout' %}"><h4>logout</h4></a></li>
        </ul>
    </div>
{% endblock %}

src/templates/pages/template-base.html
{% load static %}
<html lang="es">
<head>
    <title>Testing FLOW</title>

    <link   rel="stylesheet" 
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
            crossorigin="anonymous">

    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
            crossorigin="anonymous">
    </script>
</head>
<body>
    <div clas="container">
        <div class="row">
        {% block content %}
        {% endblock %}
        </div>
    </div>
</body>
</html>